### ISSUE TITLE
Standalone OPC UA Browser

### ISSUE THREAD

**Issue by abrasat** [convertersystems/opc-ua-tools#1]
Is the OPC UA Browser also availble as standalone application (additionally to the Visual Studio Extension) ?
What conditions must fulfill an OPC UA Server, to be "browsed" by the OPC UA Browser ? We have a custom OPC UA Server (that works fine for instance with the .NET OPC UA client samples from OPC Foundation), but it seems that the OPC UA browser cannot connect to it.

**Comment by awcullen** [comment]
Thank you for reporting this issue.
I tested with UaCPPServer and found a problem connecting to Basic128Rsa15 endpoints.
1) I will issue a new release on the Gallery, hopefully Visual Studio will inform you of an update soon.
2) Please disable Basic128Rsa15 endpoints on your custom server, they are insecure.

If you still have an issue, then please check that the server is accepting the certificate.

Also, I have not produced a standalone exe. There are so many good free clients!

**Comment by abrasat** [comment]
Thanks.
Actually the OPC UA Server that I used for my internal test had security policy "None".

**Comment by awcullen** [comment]
Could you tell me the Opc Server and the URL you were testing with?

Did you find any evidence of the Opc Server not trusting the "Workstation.UaBrowser" certificate?

**Comment by awcullen** [comment]
@abrasat. Is this issue solved?

**Comment by abrasat** [comment]
I need to take first a look into our custom OPC UA Server, but I guess the issue can be closed. Is there actually any possibility to debug the UaBrowser ?(thats why I thought a standalone UaBrowser would give the possibility to debug if necessary)

**Comment by awcullen** [comment]
Okay, now I understand.

If you have VS2017, you can debug the UaBrowser.
First, load the project. You will have to install the VS Extensibility SDK.
Switch to Debug configuration.
Rebuild the project.
Run Debug. Another instance of Visual Studio will open.
Click View... Other Windows... OPC UA Browser.  
Connect UA Browser to your custom server.
In the original instance of VS, you can see debug messages, set breakpoints, etc.

**Comment by awcullen** [comment]
Also, another test for your custom OPC server would be to run the ConsoleApp from ConverterSystems/op-ua-samples.  It connects and then browses some nodes. Let me know what output you get.

**Comment by abrasat** [comment]
Thanks for your reply. When I try to debug the UaBrowser, no other instance of VisualStudio opens, but VisualStudio pops up the message "A project with an output type of class library cannot be started directly"

**Comment by awcullen** [comment]
I'm sorry, 
On Properties page... Debug...
Start external program:
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
Command line arguments:
/rootsuffix Exp

**Comment by abrasat** [comment]
Great, it works now!
