### ISSUE TITLE
Support for Visual Studio 2015

### ISSUE THREAD

**Issue by JorundMartinsen** [convertersystems/opc-ua-tools#2]
The project can not be opened in Visual Studio 2015.

**Comment by awcullen** [comment]
I upgraded the project just recently.

If you wish to see/download the 2015 project before the upgrade, you can browse to: https://github.com/convertersystems/opc-ua-tools/tree/df56925331c4777ca342433dc56ada19be50051f

If you wish to install the UaBrowser in VS2015 or VS2017, choose Tools... Extensions and Updates and search for 'UaBrowser'.

**Comment by abrasat** [comment]
The UaBrowser VS2015 Project compiles only when referencing the 1.4.0 Workstation.UaClient release.
After updating the nuget package to Workstation.UaClient 1.5.2 version, the following compile errors are generated:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ApplicationDescription' does not contain a definition for 'GetCertificate' and no extension method 'GetCertificate' accepting a first argument of type 'ApplicationDescription' could be found (are you missing a using directive or an assembly reference?)	Workstation.UaBrowser	C:\OPCUA\opc-ua-tools\UaBrowser\ViewModels\UaBrowserViewModel.cs	504	Active
`

`Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 2: cannot convert from 'System.Security.Cryptography.X509Certificates.X509Certificate2' to 'Workstation.ServiceModel.Ua.ICertificateStore'	Workstation.UaBrowser	C:\OPCUA\opc-ua-tools\UaBrowser\ViewModels\UaBrowserViewModel.cs	535	Active
`

Are you planning to actualize the nuget package for Workstation.UaClient, after going back to VS2015 for it ?

**Comment by awcullen** [comment]
I am not planning to release a new Nuget package until I make API change or bugfix.

You should be able to debug this VS2015 project (but return UaClient to 1.4.0).
The instructions are the same as I wrote on the other question #1 

Also, another test for your custom OPC server would be to run the ConsoleApp from ConverterSystems/op-ua-samples.  It connects and then browses some nodes. Let me know what output you get.
