### ISSUE TITLE
Browse opc-ua server nodes - get data type id for variable

### ISSUE THREAD

**Issue by abrasat** [convertersystems/opc-ua-tools#3]
When iterating the opc-ua server nodes, for nodes having the NodeClass = Variable and the TypeDefinition = BaseDataVariableType, how would be possible to get their DataTypeId (from the DataTypeIds static class - >Boolean, Int16, String, Float, UtcTime and so on).
Code snippet:

> var refs = browseResponse.Results.Where(result => result.References != null).SelectMany(result => result.References).ToArray();
if (refs.Length == 0)
{
	return;
}
foreach (var aref in refs)
{
    if (aref.NodeClass == NodeClass.Variable && aref.TypeDefinition.ToString() == VariableTypeIds.BaseDataVariableType)
    {
        // get DataTypeId for variable -> how ?

**Comment by awcullen** [comment]
First, for each node, read the DataType and ValueRank attributes:
```
var nodes = refs.Select(r => ExpandedNodeId.ToNodeId(r.NodeId, this.session.NamespaceUris)).ToArray();
var readTypeRequest = new ReadRequest { NodesToRead = nodes.Select(n => new ReadValueId { NodeId = n, AttributeId = AttributeIds.DataType }).ToArray() };
var readTypeResponse = await this.session.ReadAsync(readTypeRequest);
var readRankRequest = new ReadRequest { NodesToRead = nodes.Select(n => new ReadValueId { NodeId = n, AttributeId = AttributeIds.ValueRank }).ToArray() };

var readRankResponse = await this.session.ReadAsync(readRankRequest);
```

Second, lookup the .Net Type in a dictionary of registered types:
```
NodeId dataTypeNode;
ExpandedNodeId dataTypeId;
Type dataType;
int valueRank;

dataTypeNode = readTypeResponse.Results[i].GetValueOrDefault(NodeId.Null)
dataTypeId = NodeId.ToExpandedNodeId(dataTypeNode, this.session.NamespaceUris);
if (!UaTcpSecureChannel.DataTypeIdToTypeDictionary.TryGetValue(dataTypeId, out dataType))
{
    dataType = typeof(Object); // or throw
}

```

Lastly, if ValueRank is 1 or greater, make an array:
```
valueRank = readRankResponse.Results[i].GetValueOrDefault(-1);
if (valueRank == 1)
{
    dataType = dataType.MakeArrayType();
}
if (valueRank > 1)
{
    dataType = dataType.MakeArrayType(valueRank);
}
```

**Comment by abrasat** [comment]
Great, thank you !
One more question. How can be checked if the NodeId identifier refers to a well-known server variable from the VariableIds static class (for instance some ServerStatus) ?

**Comment by awcullen** [comment]
I don't see a way to do that with the existing classes. How would that help you?

**Comment by abrasat** [comment]
For instance I could have a client that automatically subscribes to all the NodeIds containing the "ServerStatus" or the "ServerDiagnostics" string in their identifier.

**Comment by awcullen** [comment]
Okay, try:
```
var nodeIdsByName = typeof(VariableIds).GetFields().ToDictionary(f => f.Name, f => NodeId.Parse(f.GetValue(null).ToString()));
var nodeIdsWithServerStatusOrServerDiagnostics = nodeIdsByName.Where(p => p.Key.Contains("ServerStatus") || p.Key.Contains("ServerDiagnostics")).Select(p => p.Value).ToArray();
```

**Comment by abrasat** [comment]
Thank you very much !
Do you eventually have a sample how to set a opc ua subscription having a NodeId object ?

**Comment by awcullen** [comment]
See https://github.com/convertersystems/opc-ua-samples/blob/master/ConsoleApp/Program.cs

Change line 130-134 to:
```
Console.WriteLine("Step 7 - Add items to the subscription.");

var nodeIdsByName = typeof(VariableIds).GetFields().ToDictionary(f => f.Name, f => NodeId.Parse(f.GetValue(null).ToString()));
var nodeIdsWithServerStatusOrServerDiagnostics = nodeIdsByName.Where(p => p.Key.Contains("ServerStatus") || p.Key.Contains("ServerDiagnostics")).Select(p => p.Value).ToArray();

var itemsToCreate = nodeIdsWithServerStatusOrServerDiagnostics.Select((n, i) => 
    new MonitoredItemCreateRequest
    {
        ItemToMonitor = new ReadValueId { NodeId = n, AttributeId = AttributeIds.Value },
        MonitoringMode = MonitoringMode.Reporting,
        RequestedParameters = new MonitoringParameters { ClientHandle = (uint)i, SamplingInterval = -1, QueueSize = 0, DiscardOldest = true }
    })
    .ToArray();

```

**Comment by abrasat** [comment]
Thanks again.
If several items are monitored, how does the client get the NodeId of the item whose value has changed ?
Does the "session.PublishAsync()" method have to be called cyclically by the client, in view to be notified when any of the monitored items has changed ?
If yes, is there also some other possibility for the client to get notified on value changes of the monitored items, without having to poll the server with "PublishAsync" calls ?

**Comment by awcullen** [comment]
> If several items are monitored, how does the client get the NodeId of the item whose value has changed ?

You need to provide a unique ClientHandle of type uint when creating a MonitoredItem. It is the only way to identify the item that changed in the PublishResponse.

> Does the "session.PublishAsync()" method have to be called cyclically by the client, in view to be notified when any of the monitored items has changed ?

Yes. That's required by every UA Server.

> Is there also some other possibility for the client to get notified on value changes of the monitored items, without having to poll the server with "PublishAsync" calls ?

Yes.  In the samples 'StatusHmi', 'RobotHmi', MobileHmi and 'RobotApp', you can see that I use an custom api. Instead of constructing a UaTcpSessionChannel and calling CreateSubscriptionAsync / CreateMonitoredItemsAsync / PublishAsync etc.,  I  construct a UaTcpSessionClient and Subscribe 'viewModels with attributes'.

**Comment by abrasat** [comment]
> You need to provide a unique ClientHandle of type uint when creating a MonitoredItem. It is the only way to identify the item that changed in the PublishResponse.

Do the ClientHandle uint values have to be unique for a subscription, even if for instance several "groups" of monitored items are subscribed by calling the method CreateMonitoredItemsAsync() several times for the same subscription ?
I guess that the ClientHandle uint values can be the same if they are added to a second different subscription, is this correct ?
Would be possible to extend the opc ua client implementation by adding the NodeId information to the PublishResponse ?

> Instead of constructing a UaTcpSessionChannel and calling CreateSubscriptionAsync / CreateMonitoredItemsAsync / PublishAsync etc., I construct a UaTcpSessionClient and Subscribe 'viewModels with attributes'.

Thanks, I will take a look  into that.
What about the same mechanism (using UaTcpSessionClient) for a console application, where no viewModels with attributes are involved, is this also possible ? (I mean without using attributes)

**Comment by awcullen** [comment]
> Do the ClientHandle uint values have to be unique for a subscription, even if for instance several "groups" of monitored items are subscribed by calling the method CreateMonitoredItemsAsync() several times for the same subscription ?

They have to be unique for the subscription.
> I guess that the ClientHandle uint values can be the same if they are added to a second different subscription, is this correct ?

Correct.
> Would be possible to extend the opc ua client implementation by adding the NodeId information to the PublishResponse ?

The UaTcpSessionChannel follows the specification, and I have no plans to change it. For now you better keep track of your nodeIds in a ClientHandleToNodeIdDictionary or something similar.

**Comment by abrasat** [comment]
I followed your advice and am keeping track in my application of the association between the client handles and the corresponding node indentifiers.

Is there any sample available, with the usage of UaTcpSessionClient methods from a console application, without using attributes for marking the NodeIds ?

**Comment by awcullen** [comment]
Sorry, there is no sample of using UaTcpSessionClient without using attributes for marking the NodeIds. 
The reason is that the code to support subscribing with viewModels interferes with using the client for any other type of subscription.  I plan to refactor the Client to separate to concerns of the viewModels used in samples. 
I'll let you know when I have something.

**Comment by rustygutter** [comment]
I'm trying to do the same this as the OP -- determine the data types of a group of variables.  UaTcpSecureChannel.DataTypeIdToTypeDictionary to longer works and I'm struggling to figure out how achieve the same thing with the latest code.
Any suggestions would be appreciated.

**Comment by awcullen** [comment]
Hi Rusty,

You can read the DataType and ValueRank attributes as shown above.  Then you can lookup the System.Type using the new method:
```
if (!TypeLibrary.TryGetTypeFromDataTypeId(dataTypeId, out dataType))
{
    dataType = typeof(Object); // or throw
}

```

The TypeLibrary handles the structure types currently, and in the latest release, 3.0.2, it handles the built-in types like (Boolean, Float...)

**Comment by rustygutter** [comment]
Thanks, and I thought I'd share how much I appreciate your work on the library.  
FWIW, studying your code has been quite helpful in my journey to improve my otherwise pretty basic C# skills.
