### ISSUE TITLE
Controler restarted when I load many Variables in OPC Browser 

### ISSUE THREAD

**Issue by tejasklodha** [convertersystems/opc-ua-tools#4]
Dear Sir,

When i connect Controller it is working fine.
but when i load too many variable in opc Browser then PLC it self restarted.(I observ this in many times)
and also observe that OPC browser still search continually 
![screenshot_1](https://cloud.githubusercontent.com/assets/25738779/25515924/0e1bbcb4-2c05-11e7-8903-092d7bb7e0bd.png)
until i am not restarted visual studio

Detail Issue:

Attached image contain two structure that is **Global PV** and **hs1i** which is created by us
there are lots of variable of PLC in  **Global PV** more then 500 and aprox 50 variables in **hs1i**.

When I load **hs1i** then it is working fine.
But in when open **Global PV** as per attached image then PLC Restarted.

Is it annoying behavior of OPC UA Browser or may problem in PLC?
Is it any limit to show variables in OPC UA brwoser

Thanks,

**Comment by awcullen** [comment]
Which version is installed?  See Tools... Extensions and Updates...

![image](https://cloud.githubusercontent.com/assets/11900570/25530469/57645b26-2bf4-11e7-87e2-64b12c645507.png)

**Comment by tejasklodha** [comment]
I Used 1.5.9 Version

![image](https://cloud.githubusercontent.com/assets/25738779/25552560/8de1fd90-2cba-11e7-8ce2-df57b035f778.png)

**Comment by awcullen** [comment]
There is a way to write the exceptions to a file:

1. Start notepad.exe as Administrator (by right click Run as Administrator).

2. Select File...Open.  Change Filter to "All files (* .*). Change directory to  "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE".  Select "devenv.exe.config".  (If that location is not correct, you can search for 'devenv.exe' in the Taskbar, then right click and choose Open file location..."). 

3. Edit the xml to end with:
```
    <system.diagnostics>
      <trace autoflush="false" indentsize="4">
        <listeners>
          <add name="myListener" type="System.Diagnostics.TextWriterTraceListener" initializeData="C:\Users\Public\Documents\devenv.log" />
          <remove name="Default" />
        </listeners>
      </trace>
    </system.diagnostics>

  </configuration>
```
4. Save the file. Restart Visual Studio.

5. Use UABrowser and cause the crash. 

6. Use Explorer to see that the "devenv.log" file is created in "C:\Users\Public\Documents" directory.

One day, I hope to be able to test the S7-1500 in person.

**Comment by tejasklodha** [comment]
Dear sir,

I will check and let you know if i greeting some helpfull logs....


thanks :) ,

**Comment by awcullen** [comment]
If you have logs, I would love to see them, to know what specific exception.

However I have an idea what it might be,  so I uploaded a new UaBrowser version 1.5.12 that connects using lowest security available and browses a maximum of 4 tags per asynchronous call. This will reduce the memory overhead of this OPC UA server

**Comment by awcullen** [comment]
@tejasklodha Any new information to share about this?

**Comment by tejasklodha** [comment]
Dear sir,

From last week I just worked on simulator, Not Physical Device (PLC)

But I will definitely Update you when I will work with PLC....

Thanks,
Tejas Lodha

**Comment by tejasklodha** [comment]
Dear sir,


Today test again and problem not resolved....

My PLC restarted when i try to view all variables....

In mentioned previous screen shoot, Globalpv expand and my plc restated.....

**Comment by tejasklodha** [comment]
Any more information required?

**Comment by awcullen** [comment]
Could you share your plc project? In TIA Portal, you can choose File.. Archive.. Then please attach the .zap14 file to your response.
I will run your program in PLCSim Advanced for testing.

**Comment by tejasklodha** [comment]
Dear Sir,

I just enter my opc ua server(PLC) url in OPC UA Browser and my PLC is restarted.
there is no project I load.

Thanks,

**Comment by awcullen** [comment]
I am asking for your TIA Portal project (which is downloaded into your S7-1500), if possible. 
The reason is that I wish to download your TIA Portal project into my plc (simulator) and test the OPC Browser.
Thank you for your help.

**Comment by awcullen** [comment]
Hi Tejas,

Would you try updating the browser to version 1.5.14. Let me know if it fixes the problem.

Andrew

**Comment by tejasklodha** [comment]
Ok....

I will try and update you soon....

Thanks

**Comment by tejasklodha** [comment]
Same issue....

But right now I am using MatrikonOPC UA Explorer for finding node id....

But for small arrays.... Ur opc ua browser working fine....

**Comment by awcullen** [comment]
Thanks for update.
