### ISSUE TITLE
get exception: VSIXInstaller.NoApplicableSKUsException when install UaBrowser 1.5.14

### ISSUE THREAD

**Issue by huangchinlin** [convertersystems/opc-ua-tools#5]
I am using Visual Studio 2019 Community and get exception VSIXInstaller.NoApplicableSKUsException when install UaBrowser 1.5.14 by Vsix installer.

the log is in below, and could suggest how to solve it?, thank you!!

2019/5/17 下午 02:44:16 - Microsoft VSIX Installer
2019/5/17 下午 02:44:16 - -------------------------------------------
2019/5/17 下午 02:44:16 - vsixinstaller.exe version:
2019/5/17 下午 02:44:16 - 16.0.2264
2019/5/17 下午 02:44:16 - -------------------------------------------
2019/5/17 下午 02:44:16 - Command line parameters:
2019/5/17 下午 02:44:16 - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,D:\kelvin_workspace\opc-ua-tools-master\UaBrowser\bin\Debug\Workstation.UaBrowser.vsix
2019/5/17 下午 02:44:16 - -------------------------------------------
2019/5/17 下午 02:44:16 - Microsoft VSIX Installer
2019/5/17 下午 02:44:16 - -------------------------------------------
2019/5/17 下午 02:44:17 - Initializing Install...
2019/5/17 下午 02:44:17 - 擴充功能詳細資料...
2019/5/17 下午 02:44:17 - 	Identifier         : 3ebf0b3e-abaa-4161-a990-435fa37f8c69
2019/5/17 下午 02:44:17 - 	Name               : Workstation.UaBrowser
2019/5/17 下午 02:44:17 - 	Author             : Converter Systems LLC
2019/5/17 下午 02:44:17 - 	Version            : 1.5.14
2019/5/17 下午 02:44:17 - 	Description        : Supports Universal Windows Platform (UWP),  WPF, and now Xamarin.Forms. 
This extension adds a tool window for browsing the namespace of an OPC UA server.
For use with our toolkit for building HMI applications using OPC UA and Visual Studio. 
With this kit you can:
 * Browse the namespace of OPC UA servers from within the Visual Studio IDE. 
 * Drag and drop the variable, method, and event nodes onto your view model.
 * Add XAML bindings to connect your UI control properties to live data and events.

2019/5/17 下午 02:44:17 - 	Locale             : en-US
2019/5/17 下午 02:44:17 - 	MoreInfoURL        : https://github.com/convertersystems/opc-ua-tools
2019/5/17 下午 02:44:17 - 	InstalledByMSI     : True
2019/5/17 下午 02:44:17 - 	SupportedFrameworkVersionRange : [4.6,)
2019/5/17 下午 02:44:17 - 
2019/5/17 下午 02:44:17 - 	SignatureState     : Unsigned
2019/5/17 下午 02:44:17 - 	支援的產品              : 
2019/5/17 下午 02:44:17 - 		Microsoft.VisualStudio.Community
2019/5/17 下午 02:44:17 - 			Version : [14.0,16.0)
2019/5/17 下午 02:44:17 - 
2019/5/17 下午 02:44:17 - 	參考                 : 
2019/5/17 下午 02:44:17 - 		-------------------------------------------------------
2019/5/17 下午 02:44:17 - 		Identifier   : Microsoft.VisualStudio.MPF.14.0
2019/5/17 下午 02:44:17 - 		Name         : Visual Studio MPF 14.0
2019/5/17 下午 02:44:17 - 		Version      : [14.0,16.0)
2019/5/17 下午 02:44:17 - 		MoreInfoURL  : 
2019/5/17 下午 02:44:17 - 		Nested       : No
2019/5/17 下午 02:44:17 - 
2019/5/17 下午 02:44:17 - 	必要條件               : 
2019/5/17 下午 02:44:17 - 		-------------------------------------------------------
2019/5/17 下午 02:44:17 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2019/5/17 下午 02:44:17 - 		Name         : Visual Studio core editor
2019/5/17 下午 02:44:17 - 		Version      : [14.0,16.0)
2019/5/17 下午 02:44:17 - 
2019/5/17 下午 02:44:17 - 簽章詳細資料...
2019/5/17 下午 02:44:17 - 	Extension is not signed.
2019/5/17 下午 02:44:17 - 
2019/5/17 下午 02:44:17 - 正在搜尋適用的產品...
2019/5/17 下午 02:44:17 - 找到已安裝的產品 - 全域位置
2019/5/17 下午 02:44:17 - 找到已安裝的產品 - Visual Studio Community 2019
2019/5/17 下午 02:44:17 - 找到已安裝的產品 - Visual Studio Build Tools 2017
2019/5/17 下午 02:44:17 - VSIXInstaller.NoApplicableSKUsException: 此擴充功能並未安裝在任何目前已安裝的產品上。
   於 VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   於 VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   於 VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   於 VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   於 VSIXInstaller.App.Initialize()
   於 System.Threading.Tasks.Task`1.InnerInvoke()
   於 System.Threading.Tasks.Task.Execute()
--- 先前擲回例外狀況之位置中的堆疊追蹤結尾 ---
   於 Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by awcullen** [comment]
Thank you for reporting this error.  I have uploaded a new version 2.2.2 to the Market Place that supports Visual Studio 2019

Andrew

________________________________

**Comment by huangchinlin** [comment]
Thank you, Andrew.
I have installed it successfully.
