### ISSUE TITLE
Adjusting the MonitoredItem attribute

### ISSUE THREAD

**Issue by richbryant** [convertersystems/opc-ua-tools#6]
Hi,

If out of scope, please just let me know and close this - nobody expects OSS authors to do their jobs for them, i hope.

I'm currently producing an informational GUI over a system which covers 4 very similar production lines, each connected to their own Siemens S7-1500.  Since only very minor tweaks are required, the sensible way to do this is to use the same viewmodel for each line and just set a few parameters.  However, the OPC toolkit essentially hardcodes the node in the MonitoredItem attribute.

Is there any way I could make it draw from a variable along the lines of 

    [MonitoredItem(nodeId: $"ns=2;s={NameOfOfPLC}.Group.Item.Status")]

in order to accomplish this?

**Comment by awcullen** [comment]
Nice idea.  I was thinking of implementing something like this. But at the time, the customer wished I would keep four similar viewModels.  Why? Because they liked how the four viewModels would continue collecting data for trend line, even when not _visible_.

Andrew

**Comment by richbryant** [comment]
That's an important consideration, and one I hadn't thought about.
